print("Bonjour, je suis une calculatrice mathématique interactive. Pouvez-vous me donnez votre nom pour que s'avoir comment vous appeler?")
nom= input()
print("Merci", nom,",vous pouvez maintenant insérer deux nombre de n'importe type pour les multiplier ensemble." )
x=input()
y=input()
float_x=float(x)
float_y=float(y)
print("La réponse de votre multiplication est,",float_x*float_y)
print("Merci,", nom, "et bonne journée")