#Ceci est le lieu de travail de Samir Abou Serhal pour le travail d'input et opération. Ce fichier fut créer le 28 Novembre 2020 pour le cours ICS3UA-01/51.
print("Bonjour, je suis une calculatrice mathématique interactive. Pouvez-vous me donnez votre nom pour que je puisse s'avoir comment vous vous appelez?")
nom= input()
print("Merci", nom,",vous pouvez maintenant insérer deux nombres de n'importe quel type pour les multiplier ensemble." )
x=input()
y=input()
float_x=float(x)
float_y=float(y)
print("La réponse de votre multiplication est,",float_x*float_y)
print("Merci,", nom, "et bonne journée.")